### ISSUE TITLE
Suplemental missing?

### ISSUE THREAD

**Issue by lJoublanc** [underscoreio/advanced-scala#110]
On the book web page there is mention of _Supplemental_ but it's not at all clear how to access it?

> Essential Interpreters covers the construction of interpreters in three styles: classic untyped interpreters, monadic interpreters, and composable interpreters using the free monad. Interpreters are the primal functional programming pattern. To quote Haskell luminary Don Stewart “almost all designs fall into the ‘compiler’ or ‘interpreter’ pattern, using a model of the data and functions on that data”.

Is this supposed to be available to early-access subscribers?

**Comment by davegurnell** [comment]
Thanks for the spot. Essential Interpreters is incomplete at this stage. This reference should be removed.

**Comment by davegurnell** [comment]
I've removed these references for now. For the record, we do plan to finish and release Essential Interpreters but we don't currently have a development timeframe.
