### ISSUE TITLE
tailRecM purpose is unclear, implementation for Tree is broken

### ISSUE THREAD

**Issue by voidunit** [underscoreio/advanced-scala#111]
I saw the discussion in #80 but I think it needs a separate issue ticket.

I find the whole `tailRecM` topic in the `Monads` chapter very confusing and misleading. So misleading that I misunderstood its real purpose and even had to rewrite this post from scratch.

First of all, it is unclear what `tailRecM` is used for and how it saves a developer from `StackOverflowError`.
Although it is mentioned that `tailRecM` is needed for stack-safe nested calls to `flatMap`, e.g. for folding over large lists, there's no further explanation in section 7.1.  

Actually `tailRecM` is used for _monadic_ operations such as `foldM` and `whileM`, which are not covered in the book. Probably it's no use to implement `tailRecM` in section 4.10, especially in such a tricky (and buggy) way. We don't even show what problem it solves. Why confuse readers?

Maybe we'd better keep it unimplemented here and return back to this function in section 7.1?
There we may introduce the monadic fold and add an exercise to implement `tailRecM` for some monad, e.g. `Tree` from section 4.10.

The example below may be used as an explanation of `foldM` and `tailRecM`:
```scala
// let's create 3 optional values
val op1 = Some(1)
val op2 = Some(2)
val op3 = Some(3)

// we can sum them up using for-comprehension
val res1 =
  for {
    i <- op1
    j <- op2
    k <- op3
  } yield i + j + k
// res1: Option[Int] = Some(6)

// which is equivalent to nested flatMaps
val res2 =
  op1.flatMap(i =>
    op2.flatMap(j =>
      op3.map(k => i + j + k)
    )
  )
// res2: Option[Int] = Some(6)

// but if we have an arbitrary list of options, we cannot write an explicit for
def listOfOptions(n: Int): List[Option[Int]] =
  (1 to n).map(Option(_)).toList

// and that's where we need `foldM` function, which uses `tailRecM` under the hood
val res3 = listOfOptions(3).foldM(0)((s, o) => o.map(s + _))
// res3: Option[Int] = Some(6)

// and it is stack-safe for (almost?) all monads in Cats including Option
val res4 = listOfOptions(10000).foldM(0)((s, o) => o.map(s + _))
// res4: Option[Int] = Some(50005000)
```

Secondly, I found a flaw in the stack-safe `tailRecM` version for `Tree` added to section 4.10 by @davegurnell. I know this solution was proposed by @nbardiuk on [StackOverflow](https://stackoverflow.com/questions/44504790/cats-non-tail-recursive-tailrecm-method-for-monads), so I invite Nazarii to join the discussion.

The implementation uses lists to store tree elements, but it loses the original tree structure, so the resulting tree is always left-skewed. A correct implementation must give the same result of folding trees as for-comprehension does. The naive `tailRecM` implementation works correctly, but it is not tail recursive. We either need to fix the tricky implementation and put it in the `Foldable` chapter as an exercise solution or choose another (simpler) monad for the exercise.

Example implementations of `tailRecM` in [Cats](https://github.com/typelevel/cats) (using mutable builders) make me think it's a much harder problem.

**Comment by phderome** [comment]
If this is being reviewed and addressed, note minor issue #115 for which I may submit a PR.

**Comment by davegurnell** [comment]
Thanks for this. I agree that the discussion of `tailRecM` is pretty inadquate (partly because I still don't really have a good handle on it myself). I'll incorporate this feedback when I do my next pass over the content prior to the print-on-demand release.

**Comment by noelwelsh** [comment]
Thanks for the extensive bug report. I've updated that section so it is hopefully clearer about what is going on.
