### ISSUE TITLE
Chapter 1 Structure

### ISSUE THREAD

**Issue by noelwelsh** [underscoreio/advanced-scala#12]
Chapter 1 introduces the basic patterns we'll be building on:
- algebraic data types and structural recursion;
- sequencing computations (`map`, `flatMap`, and `fold`); and
- type classes

This should look very much like the material in Essential Scala. These should be _briefly_ introduced, with possibly more material on type classes than the others. Essential Scala of course provides more information.

There are two other patterns to cover:
- type aliases, covered in #6; and
- type wrappers (`AnyVal`s)

**Comment by davegurnell** [comment]
I'm going to retire this issue as I no longer think it is relevant. We cover type aliases elsewhere in the book and... well, it's marginal, but I don't think we need a discussion of `AnyVals` here.
