### ISSUE TITLE
Write null instead of return JsNull?

### ISSUE THREAD

**Issue by janekdb** [underscoreio/advanced-scala#146]
https://github.com/underscoreio/scala-with-cats/blob/develop/src/pages/type-classes/implicits.md

Should the `None` case write `null`?

![image](https://user-images.githubusercontent.com/1123855/47784378-4955da80-dcfd-11e8-865f-b83fc9516dc9.png)

**Comment by noelwelsh** [comment]
Agreed; as you say we should write "return `JsNull`" so we don't confuse the JSON `null` with the Scala `null`.

**Comment by noelwelsh** [comment]
Thanks for reporting this!

**Comment by janekdb** [comment]
@noelwelsh I've misunderstood the example. The example looks fine as-is.

**Comment by janekdb** [comment]
@noelwelsh Okay, I see the text description was changed. That makes sense! Thanks.
