### ISSUE TITLE
Validation case study: Transforming data begins with `Either` rather than `Validated`

### ISSUE THREAD

**Issue by mmynsted** [underscoreio/advanced-scala#153]
In the _Validation Case Study_, the [Transforming data](https://github.com/underscoreio/scala-with-cats/blob/develop/src/pages/case-studies/validation/map.md) section begins with a description of how there are not enough types to actually perform a transformation. This makes sense but `Either` is used in the examples here. Just before this section was a the addition of the `or` combinator, and before that was converting from using `Either` to using `Validated`.

Example from the _Transforming data_ section:

>To implement `map` we need to change the definition of `Check`.
Specifically, we need to a new type variable
to separate the input type from the output:

```scala
type Check[E, A, B] = A => Either[E, B]
```

Then later in the `Predicates` section `Validated` is again used. 

I propose that `Validated` be used throughout [this](https://github.com/underscoreio/scala-with-cats/blob/develop/src/pages/case-studies/validation/map.md) document, rather than `Either`.

**Comment by mmynsted** [comment]
I can't assign it to myself so If you agree with this issue please assign it to me.

**Comment by davegurnell** [comment]
Thanks for looking at this @mmynsted. I think in the medium term we need to rewrite this and parts of the monads/applicatives chapters to use `Parallel`.

**Comment by mmynsted** [comment]
Ah yes. I see your issue here [#103](https://github.com/underscoreio/scala-with-cats/issues/103).

**Comment by mmynsted** [comment]
Sigh. I have no idea what I thought needed to be changed here. Could this one be closed? 
Perhaps time would be better spent on [#103](https://github.com/underscoreio/scala-with-cats/issues/103).

**Comment by davegurnell** [comment]
No worries -- thanks for closing.

👍  to #103. Some day I'll get time... some day!
