### ISSUE TITLE
Updates for Second Edition

### ISSUE THREAD

**Issue by davegurnell** [underscoreio/advanced-scala#170]
This is an aggregator thread to track planned updates for a second edition of the book. High level planning should go here, and individual updates should be tracked in their own issues.

In preliminary discussions, @noelwelsh, @arosien and I have discussed a few things we'd like to do:

1. Change the build system to mdoc

2. Update to Cats 2.0

3. Discuss `Parallel` and modify our discussion of `Validated` accordingly. I tend to stick to `Either` all the time these days, using `parMapN`, `parTraverse`, and so on to do parallel combination.

4. Add introductory content on Cats Effect. Possibly just a discussion of the basic type classes and `IO`. Other books/material can use this as a  starting point to bridge further into, FS2, Monix, HTTP4s, and so on.

Is this a complete list? Is there anything else we want to cover?

**Comment by noelwelsh** [comment]
I'm currently working on the conversion to `mdoc`. I think we should consider creating a separate web site for the book now that Inner Product is getting involved.

**Comment by noelwelsh** [comment]
My current progress is on `feature/mdoc`.

**Comment by arosien** [comment]
I have started a `cats-effect` [version of the exercise solutions](https://github.com/arosien/scala-with-cats-with-cats-effect/blob/master/src/main/scala/com/innerproduct/chapter8.scala).

**Comment by noelwelsh** [comment]
`feature/mdoc` is merged.

**Comment by noelwelsh** [comment]
I've opened a project for the update, which will be easier to work with. Closing this in preference to the project.

**Comment by asarkar** [comment]
Came across this thread from [this](https://underscore.io/blog/posts/2020/05/27/scala-with-cats-2.html) blog post. Given that this ticket was closed, is there a way for interested readers to stay informed on the progress of the new book?

**Comment by davegurnell** [comment]
Hey @asarkar. Sure! You can follow along by joining the newsletter at https://scalawithcats.com/.

**Comment by asarkar** [comment]
I'm not interested in the newsletter, thanks. Since the website states that work on the book is ongoing, and this ticket was created 4 years ago, I thought there might be a way to find out an expected release date, if any.

**Comment by noelwelsh** [comment]
Sorry, there's no expected release date at this point. If you don't want to receive the newsletter, following the commits to the repository is the next best option.
