### ISSUE TITLE
3.2: Rob Norris answer is on Reddit not SO

### ISSUE THREAD

**Issue by marko-asplund** [underscoreio/advanced-scala#171]
this is on page 51

**Comment by arosien** [comment]
I see a reference to Reddit in [the online version section 3.2](https://books.underscore.io/scala-with-cats/scala-with-cats.html#sec:functors:more-examples). Do you perhaps have a different version, that may have been corrected?

**Comment by marko-asplund** [comment]
I'm reading PDF version "November 2017":

<img width="685" alt="Screenshot 2020-01-15 at 21 25 29" src="https://user-images.githubusercontent.com/1002541/72464274-9a0c0300-37dd-11ea-9dfd-2e7f67cf0f24.png">

**Comment by marko-asplund** [comment]
Seems to have been fixed in the online version.
