### ISSUE TITLE
Mentioned scala.language import not present

### ISSUE THREAD

**Issue by janekdb** [underscoreio/advanced-scala#175]
https://www.scalawithcats.com/dist/scala-with-cats.html#definition-of-a-functor

> If you haven’t seen syntax like F[_] before, it’s time to take a brief detour to discuss type constructors and higher kinded types. We’ll explain that scala.language import as well.

There isn't a scala.language import in this section.

**Comment by noelwelsh** [comment]
Thanks for reporting this. It's now fixed.
