### ISSUE TITLE
Reformat `Readers` as `Reader`s, etc?

### ISSUE THREAD

**Issue by FranklinChen** [underscoreio/advanced-scala#185]
Throughout the rendered book I see code-formatted text such as `Readers` but think it would make more sense for it to be `Reader`s. This would be a far-reaching global change, though, e.g., `Ints` would become `Int`s, etc.

**Comment by noelwelsh** [comment]
I think we'll keep the formatting as it currently is. I prefer how `Ints` renders compared to `Int`s and I don't believe it is that confusing to readers.
