### ISSUE TITLE
Confounding example on `MonadError.handleError`

### ISSUE THREAD

**Issue by yhpark** [underscoreio/advanced-scala#187]
In Ch. 4.5.2, the book shows a simple example of using `handleError` method, which maps the error type `String` to `ErrorOr[String]` so the resulting type is nested `ErrorOr[ErrorOr[String]]` which possibly confound readers to think `handleError` takes `E => F[A]`. I would change the example to `handleError` returns some `Int` instead of `ErrorOr[String]` because it's simpler and coherent with the previous code example.

**Comment by yhpark** [comment]
Also I found the exercise `4.5.4 Exercise: Abstracting` empty. Seems it's been left unfinished since the initial writing 3 years ago

**Comment by noelwelsh** [comment]
Thanks. I've fixed it now.
