### ISSUE TITLE
Status on scala with cats 2?

### ISSUE THREAD

**Issue by fierepony** [underscoreio/advanced-scala#239]
Hi there. This might not be the best place to ask about this, but I thought it would be the easiest place to contact the authors or anyone working on the project.

I was curious about what the status is on the second version of the book. I've just subscribed to the emailing list to get updates and when I looked at the archive, I saw that there were only 3 emails, the last sent in july 2020. Since that's almost 3 years ago, I was wondering: is the second version of the book cancelled or are the authors just too busy with other projects?

Thanks in advance for taking the time to reply and have a nice day!

**Comment by noelwelsh** [comment]
It's about to become active again. Should be an update next week.

**Comment by noelwelsh** [comment]
If you're on the mailing list you'll have seen the update. If not: https://noelwelsh.com/posts/books-update/

**Comment by fierepony** [comment]
I've got the mail, thanks!
