### ISSUE TITLE
Implementation of scanLeft in Chapter 3.3 does not match behaviour of List

### ISSUE THREAD

**Issue by Sorixelle** [underscoreio/advanced-scala#256]
"Exercise: Stream Combinators" asks:

> Implement [...] scanLeft on Stream. They have **the same semantics as the same methods on List,** [...]

The behaviour of `List`s `scanLeft` is as follows:

```scala
scala> def increment(x: Int, y: Int): Int = x + y
def increment(x: Int, y: Int): Int

scala> List.fill(5)(1).scanLeft(0)(increment)
val res0: List[Int] = List(0, 1, 2, 3, 4, 5)
```

However, using the solution provided by the book for `Stream` gives the following result (using the book's prior definition of `ones`):
```scala
scala> def increment(x: Int, y: Int): Int = x + y
def increment(x: Int, y: Int): Int

scala> ones.scanLeft(0)(increment).take(6)
val res0: List[Int] = List(1, 2, 3, 4, 5, 6)
```

The difference being that while `List`'s `scanLeft` includes the `zero` value in the resulting `List` as-is, `Stream`'s does not, instead applying `f` to `zero` and `self.head` as the first element of the resulting `Stream`. An implementation of `scanLeft` for `Stream` that follows the one in `List` could instead look like:

```scala
def scanLeft[B](zero: B)(f: (B, A) => B): Stream[B] = {
  val self = this
  new Stream[B] {
    def head: B = zero
    def tail: Stream[B] = self.tail.scanLeft(f(zero, self.head))(f)
  }
}
```

**Comment by asarkar** [comment]
I made the same observation.

**Comment by noelwelsh** [comment]
Thanks. I've fixed this. Please submit a PR w/ your name in acknowledgements.md if you'd like to have your name in the book.
