### ISSUE TITLE
Wording is not clear on excercise

### ISSUE THREAD

**Issue by agaro1121** [underscoreio/advanced-scala#50]
[invariant.md](https://github.com/underscoreio/advanced-scala/blob/22efd70d5fa4274d4fe09331c17ad1f86af6d593/src/pages/functors/contravariant-invariant.md)
3.6 CONTRAVARIANTANDINVARIANTFUNCTORS (Page 69)
"Rather than writing out the complete definition from scratch (new Printable[Box] etc...), create your instance using the contramap method of one of the instances above."

Might be more clear to say something like:
"Rather than writing out the complete definition from scratch (new Printable[Box] etc...), create your instance [,in a generic way,] using the contramap method [that will work for any instance]."

**Comment by davegurnell** [comment]
Thanks for this. I'll look into incorporating the changes soon.
