### ISSUE TITLE
Backlinks from solutions

### ISSUE THREAD

**Issue by kosgdk** [underscoreio/advanced-scala#59]
I think that backlinks from solutions should lead each one to its corresponding subsection of exercise, but not to the beginning of whole exercise.

For example: **A.3 Printable Library Part 3** backling should lead to **Better Syntax** subsection instead of  **1.1.4 Exercise: Printable Library**

**Comment by davegurnell** [comment]
This is a limitation in the ebook template. I've moved the ticket there:

https://github.com/underscoreio/underscore-ebook-template/issues/19
