### ISSUE TITLE
API reference problem (1.3.1)

### ISSUE THREAD

**Issue by kosgdk** [underscoreio/advanced-scala#60]
### 1.3.1 Equality, Liberty, and Fraternity

> The interface syntax, defined in **[cats.syntax.equal][cats.syntax.equal]**,
> provides two methods for performing type-safe equality checks pro-
> vided there is an instance Eq[A] in scope:

**Comment by seoh** [comment]
It was fixed(#51). If you compile book again, you can get the right one :)

**Comment by kosgdk** [comment]
So, the version at [http://underscore.io/books/advanced-scala/](http://underscore.io/books/advanced-scala/) does not contain latest fixes?

**Comment by davegurnell** [comment]
Sorry for the confusion here and thanks for the bug report!

When we release to Gumroad we send an email to everyone who has downloaded a copy of the book (and not opted out of update emails, of course). For this reason, we often a while between updates.

I'm working on a Cats 1.0-MF release right now. It should go out on Gumroad this week.
