### ISSUE TITLE
Table header align (2.6.1)

### ISSUE THREAD

**Issue by kosgdk** [underscoreio/advanced-scala#61]
### 2.6.1 Type Class Variance

![image](https://user-images.githubusercontent.com/16893004/28040804-b004864c-65cf-11e7-8758-ae7f8a22d78d.png)

**Comment by davegurnell** [comment]
This one's rendering correctly in the current version of the book. I'll close the ticket optimistically!

![image](https://user-images.githubusercontent.com/231655/30270164-7eb5ec30-96e3-11e7-8fe0-e161bea2c2a5.png)

(The yellow highlight is because I was searching for it in Preview.)
