### ISSUE TITLE
"Validated" exercise typos

### ISSUE THREAD

**Issue by PeterPerhac** [underscoreio/advanced-scala#64]
page 165

- `readName` will take a Map[String, String] parameter, extract the "name" field, check the relevant validation rules, and return an Either[List[String, String]];
- `readAge` will take a Map[String, String] parameter, extract the "age" field, check the relevant validation rules, and return an Either[List[String, Int].

return types brackets need rebalancing. First line has a misplaced closing bracket, second line is missing one.

first should be `Either[List[String], String]`, second should be `Either[List[String], Int]`

**Comment by davegurnell** [comment]
Good spot. Thanks!

It looks like a kindly contributor has supplied a fix: 2ed72d5a.
