### ISSUE TITLE
Variance annotations

### ISSUE THREAD

**Issue by ccheneson** [underscoreio/advanced-scala#72]
Under the section "Controlling Instance Selections", it recaps 3 cases for addition of variance annotations:

> A type with an unannotated parameter Foo[A] is invariant in A .
> This means there is no rela onship between Foo[B] and Foo[C]
> no ma er what the sub- or super-type rela onship is between B
> and C .
> • A type with a parameter Foo[+A] is covariant in A .
> If C is a subtype of B , Foo[C] is a subtype of Foo[B] .
> • A type with a parameter Foo[-A] is contravariant in A .
> If C is a supertype of B , Foo[C] is a subtype of Foo[B] .

Should the last statement be 
>  If C is a supertype of B , Foo[C] is a supertype of Foo[B] .

**Comment by davegurnell** [comment]
Contravariance works the other way around. Take a look in Essential Scala
in the section on variance. That should explain it.

**Comment by ghisvail** [comment]
> If C is a supertype of B , Foo[C] is a subtype of Foo[B]

This the correct definition of contravariance. See `essential-scala` section `5.6.1` which briefly mentions that contravariance is used for function arguments. The issue should be closed.

**Comment by cchphotobox** [comment]
Thanks for your response. It seems I can not close this issue (No "Close" button). Sorry for the misunderstanding

**Comment by davegurnell** [comment]
@ccheneson @cchphotobox No worries -- thanks for submitting the issue. You're not the first to mention this. Variance is one of the more esoteric parts of Scala's type system -- it confuses loads of people.

In fact, I think I'll add a note to clarify the situation. If it's being picked up by multiple people, it's worth addressing directly. I'll leave this ticket open as a reminder.

Please do post again if you spot anything else -- every bit of feedback is useful!

**Comment by davegurnell** [comment]
I've made two changes in c7cf137 in an attempt to improve the clarity here:

- I've changed the wording in the definitions so they both say "subtype" in all places, instead of mixtures of "subtype" and "supertype".

- I've added some quick examples.

If you have time, please let me know what you think!
