### ISSUE TITLE
Solution to Folding Using Eval

### ISSUE THREAD

**Issue by davegurnell** [underscoreio/advanced-scala#82]
Bug spot from @micahkim23 on Gitter:

> In the Advanced Scala Cats book, the solution 12.4.4 Safer Folding Using Eval, the example at the end is wrong

```scala
foldRight((1 to 100000).toList, 0)(_ + _)
// res22: Int = 705082704
```

> Summing up 1 to 100000 should equal 100000* 100001/2, should probably use a Long here

**Comment by davegurnell** [comment]
Heh. You're absolutely right. I should totally have spotted that one. Thanks!

**Comment by micahkim23** [comment]
This issue is also in section 7.1.4.1 Folding Right
`eval.value
// res10: Int = 705082704`

`(1 to 100000).toList.foldRight(0)(_ + _)
// res11: Int = 705082704`

`(1 to 100000).toVector.foldRight(0)(_ + _)
// res12: Int = 705082704`
