### ISSUE TITLE
Chapter 3.2 Function Functors and Scala 2.12

### ISSUE THREAD

**Issue by eddsteel** [underscoreio/advanced-scala#85]
I'm working through the book with scala 2.12 and cats 1.0.0-MF (stop me there if this is known to be a bad idea). There seems to be an issue with scala 2.12's use of lambdas (I'm guessing) and cats function Functor instances; following the examples doesn't work.

```
scala> import cats.instances.function._
import cats.instances.function._

scala> import cats.syntax.functor._
import cats.syntax.functor._

scala> val func1 = (x: Int) => x.toDouble
func1: Int => Double = $$Lambda$1019/1377456236@4eb1943b

scala> val func2 = (y: Double) => y * 2
func2: Double => Double = $$Lambda$1020/1094732450@b267745

scala> func1.map(func2)
<console>:20: error: value map is not a member of Int => Double
       func1.map(func2)
             ^
```

But if I alias a new type I can get and use the Functor instance.

```
scala>  type F1[X] = Function1[Int, X]
defined type alias F1

scala> val func3 = Functor[F1].map(func1)(func2)
func3: F1[Double] = scala.Function1$$Lambda$1187/903151311@4d4ae76

scala> func3(1)
res14: Double = 2.0

scala> func2(func1(1))
res15: Double = 2.0
```

**Comment by eddsteel** [comment]
This applies to section 3.5.2 as well.

**Comment by davegurnell** [comment]
Thanks for the bug report!

This is undoubtedly a partial type constructor unification thing. Your
success with a type alias pretty much confirms it.

Partial unification is an optional feature in certain versions of the
compiler. I haven't yet updated the start of the book with the necessary
information. Can you try with scalacOptions += "-Ypartial-unification" and
see if that helps?

**Comment by eddsteel** [comment]
Thanks! That does indeed fix it. 

I already had that in my SBT definition but my editor plugin was giving me a repl without the flag applied, running from `sbt console` worked.

**Comment by davegurnell** [comment]
Great! I'll leave this here to remind me to go into more detail. As I
remember there is a section talking about this... I think contravariant
functors applied to functions is the bit... but we need some up-front
guidance on compiler versions and settings.

**Comment by eddsteel** [comment]
I just cloned the book and there's a whole section there discussing this, it's just not in the version I downloaded. So I think you may already have this covered!

EDIT: rebuilt the book, this note is in exactly the right place.

**Comment by davegurnell** [comment]
Groovy. I'll be rolling that version out on Gumroad later this week. Need
to do a bunch of proof reading first :)

**Comment by noelwelsh** [comment]
Looks like we can close this one.
